### ISSUE TITLE
perf.r-l.o fails to load with 504 Gateway Time-out

### ISSUE THREAD

**Issue by jonhoo** [rust-lang-nursery/rustc-timing#10]
Is this a known issue?
https://perf.rust-lang.org/

**Comment by Mark-Simulacrum** [comment]
Yeah, I think we've hit some limit in terms of amount of data and it's just big enough that storing it all in memory is beginning to be non-viable for our (relatively) small machine. I'm working on a series of patches to try and help with that right now.

**Comment by jonhoo** [comment]
Will your changes affect the storage layout in this repository? I just updated https://github.com/jonhoo/rust-at-sunrise/ to match the new non-string, compressed format.

**Comment by Mark-Simulacrum** [comment]
It's quite plausible, yes. Not sure yet exactly what we're going to move towards, though, so hard to tell.

**Comment by jonhoo** [comment]
Would you mind posting again here when the changes are done so I can update accordingly?

**Comment by Mark-Simulacrum** [comment]
Well, initial round did not require any further changes to storage format (though internal data structures changed). Probably going to need to spend some more time over the next several days and I'll try to keep this thread updated.

**Comment by jonhoo** [comment]
Thanks! When you say internal data structures, you mean the in-memory structures, right? If so, no changes should be necessary for my tool for the time being at least. And thanks, I appreciate it if it's not too much hassle!

**Comment by Mark-Simulacrum** [comment]
Yes, in memory structures. Shouldn't be too much hassle.
