### ISSUE TITLE
Is this repository expected to stick around?

### ISSUE THREAD

**Issue by jonhoo** [rust-lang-nursery/rustc-timing#6]
I notice there's been some work on [`perf2.0`](https://github.com/rust-lang-nursery/rustc-perf/commits/perf2.0); is that something that's going to result in this repository no longer being maintained? I maintain a Twitter bot ([@rust_at_sunrise](https://twitter.com/rust_at_sunrise)) that announces new nightlies including performance changes, and [rely on](https://github.com/jonhoo/rust-at-sunrise/blob/master/src/main.rs#L184) this repository to get that information (the perf.rlo API didn't seem very stable). I know it's not exactly a repository that's supposed to be user facing, but it'd still be nice to hear what the longer-term plans are for it :)

**Comment by Mark-Simulacrum** [comment]
This repository will stick around, but the file format is inherently unstable. I hope to get your bot and others a more stable API soon (commit to commit SHA diffs).

**Comment by jonhoo** [comment]
If I can put in a feature request, the most important API for me is the ability to look at the performance diff between two points in time. I don't necessarily have an exact commit (I mean, I do, but it may be that no perf was run for that commit), but want to compare the results *closest* to some start and end date/commit.

**Comment by jonhoo** [comment]
@Mark-Simulacrum any updates on this, or issues/PRs I should be watching? I notice new perf results haven't been posted here for a few days...

**Comment by Mark-Simulacrum** [comment]
Sorry, not yet. I'm mostly happy to take PRs to add an API endpoint to perf.rlo (rust-lang-nursery/rustc-perf) and if merged I'd be happy to maintain something like it. Maybe you'd like to write a description for it?
