### ISSUE TITLE
The `times/` directory is growing quite large

### ISSUE THREAD

**Issue by jonhoo** [rust-lang-nursery/rustc-timing#7]
Might it be an idea to, say, create one folder per year? Or maybe per month? And then stuffing all the results inside those. Would make the repository easier to browse, and make things like `ls` less painful. Even when writing programs that operate on these files, there are now *a lot* of files to scan through (and there'll only be more over time), even if you know what date you're looking for..

**Comment by Mark-Simulacrum** [comment]
Yes, I've thought about moving away from storing individual file for each commit. I'm not really sure how much of a problem it is to have lots of file in the same directory, though... it's not really intended for `ls` or browsing by-hand.

**Comment by bjorn3** [comment]
> I'm not really sure how much of a problem it is to have lots of file in the same directory, though... it's not really intended for ls or browsing by-hand.

Every time you add a file to a directory in a commit, there git will generate a new tree object whose size is proportional to the amount of files in that directory. If you have say 1 million file, then every new file will create a tree object containing 1 million entries. By grouping for all commits of a month, the new tree objects will be a lot smaller.

Maybe it would be an idea to instead create a tag/branch for every benched commit. In case of a tag, it would not even have to point to a commit. It can also point to the blob object itself. For example the git repo has the sign key as a tag.
